In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
df = pd.read_csv(r'data.csv')

C:\Users\dell\AppData\Local\Temp\ipykernel_22216\1578770654.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'data.csv')


In [3]:
df.head()

,label,left_x0,left_y0,left_z0,left_x1,left_y1,left_z1,left_x2,left_y2,left_z2,...,right_z17,right_x18,right_y18,right_z18,right_x19,right_y19,right_z19,right_x20,right_y20,right_z20
0,1,0.4869,0.8742,-0.0,0.4043,0.7801,-0.0647,0.3655,0.6604,-0.1167,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,1,0.4844,0.8761,-0.0,0.4018,0.7844,-0.0649,0.3639,0.6648,-0.1170,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,1,0.4876,0.8747,-0.0,0.4037,0.7814,-0.0619,0.3652,0.6610,-0.1105,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,1,0.4712,0.8725,-0.0,0.3961,0.7755,-0.0647,0.3521,0.6534,-0.1209,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,1,0.4950,0.9048,-0.0,0.4183,0.8031,-0.0961,0.3921,0.6673,-0.1616,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0


In [4]:
df['label'] = df['label'].astype(str)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41674 entries, 0 to 41673
Columns: 127 entries, label to right_z20
dtypes: float64(126), object(1)
memory usage: 40.4+ MB


In [6]:
df['label'].unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D',
       'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q',
       'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'], dtype=object)

In [6]:
df['label'].value_counts()

label
I    1379
O    1313
C    1294
V    1285
H    1200
Y    1200
X    1200
W    1200
T    1200
R    1200
N    1200
M    1200
L    1200
K    1200
J    1200
2    1200
1    1200
8    1200
F    1200
3    1200
4    1200
5    1200
6    1200
7    1200
Z    1200
A    1200
D    1200
E    1200
9    1199
U    1199
G    1199
B    1187
P    1186
S     856
Q     777
Name: count, dtype: int64

In [7]:
df.isna().sum().sum()

0

In [8]:
X = df.iloc[:, 1:].values
Y = df.iloc[:, 0].values

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

y_encoded = le.fit_transform(Y)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y_encoded, test_size = 0.3, random_state = 42)

In [11]:
print(f"Training Samples:", len(X_train))
print(f"Testing Samples:", len(X_test))
print(f"Total Signs:", len(le.classes_))

Training Samples: 29171
Testing Samples: 12503
Total Signs: 35


In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [13]:
models = {
    'rf': RandomForestClassifier(n_estimators = 100, random_state = 42),
    'svc' : SVC(kernel = 'rbf', C = 10, gamma = 'scale'),
    'KNN' : KNeighborsClassifier(n_neighbors = 5)
}

In [14]:
results = {}

In [15]:
for name, model in models.items():
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(Y_test, y_pred)
    results[name] = acc
    print(f"Model: {model}, Accuracy: {acc:.2f}")

Model: RandomForestClassifier(random_state=42), Accuracy: 1.00
Model: SVC(C=10), Accuracy: 1.00
Model: KNeighborsClassifier(), Accuracy: 1.00


In [16]:
best_model_name = max(results, key = results.get)
print(f"\nBest Model: {best_model_name} → {results[best_model_name]*100:.2f}%")


Best Model: rf → 99.92%


In [17]:
best_model = models[best_model_name]
y_pred = best_model.predict(X_test)

print(classification_report(Y_test, y_pred, target_names = le.classes_))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       366
           2       1.00      1.00      1.00       381
           3       1.00      1.00      1.00       369
           4       1.00      1.00      1.00       373
           5       1.00      1.00      1.00       367
           6       1.00      1.00      1.00       389
           7       1.00      1.00      1.00       390
           8       1.00      1.00      1.00       359
           9       1.00      1.00      1.00       337
           A       1.00      1.00      1.00       341
           B       1.00      1.00      1.00       384
           C       0.99      0.99      0.99       386
           D       1.00      1.00      1.00       359
           E       1.00      1.00      1.00       336
           F       1.00      1.00      1.00       317
           G       1.00      1.00      1.00       363
           H       1.00      1.00      1.00       366
           I       1.00    

In [18]:
print(confusion_matrix(Y_test, y_pred))

[[366   0   0 ...   0   0   0]
 [  0 381   0 ...   0   0   0]
 [  0   0 369 ...   0   0   0]
 ...
 [  0   0   0 ... 365   0   0]
 [  0   0   0 ...   0 379   0]
 [  0   0   0 ...   0   0 336]]


In [19]:
import pickle

In [20]:
with open(r'models/isl-model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

with open(r'models/label-encoder.pkl', 'wb') as f:
    pickle.dump(le, f)